name: build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: go build -v -o app main.go

      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          files: workers-manager
          body: "Автоматическая сборка для версии ${{ github.ref_name }}"